version: 0.0.1.{build}-{branch}
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1604
  - Ubuntu1804
  - Ubuntu2004
  - macos
  - macos-mojave

environment:
  LeetABitBuild_ForceInstallPowerShell: 1
  matrix:
    - ARCH: arm
    - ARCH: arm64
    - ARCH: amd64

matrix:
  exclude:
    - image: Visual Studio 2013
      ARCH: arm
    - image: Visual Studio 2013
      ARCH: arm64
    - image: Visual Studio 2015
      ARCH: arm
    - image: Visual Studio 2015
      ARCH: arm64
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64
    - image: Visual Studio 2019
      ARCH: arm
    - image: Visual Studio 2019
      ARCH: arm64
    - image: macos
      ARCH: arm
    - image: macos
      ARCH: arm64
    - image: macos-mojave
      ARCH: arm
    - image: macos-mojave
      ARCH: arm64

install:
build_script:
  - cmd: run.cmd help
  - sh: ./run.sh help
test: off
